### PR TITLE
added dist directory

### PR DESCRIPTION
**Pull request by tyage**
- Add builded css in repository
  - So that `machiya-ui` can be used with bower
- Add license comment in css

### CODE REVIEW

**Comment by masawada** [comment]
I felt minified css should be managed as binary file.
https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by tyage** [comment]
:walking:

**Comment by tyage** [comment]
Check it plz

**Comment by masawada** [comment]
[LGTM](http://lgtm.in/i/uLglTz7aq)

**Pull request merged**
